### ISSUE TITLE
Дальше впечатление, что остальные задания списаны у Колчанова

### ISSUE THREAD

**Issue by slemeshevsky** [Spinningcrane/Python-Labs#5]

**Comment by Spinningcrane** [comment]
Я действительно взял некоторые задания у Колчанова, но предварительно разобрался в них. Если необходимо это подтвердить, то готов переделать все с нуля, мне хватит одного вечера. Однако вы в полном праве не засчитать задания, потому что я поступил неправильно.

**Comment by slemeshevsky** [comment]
А почему бы не сделать другие задания? Тем более, я на сайте написал, что
до 9 января можно поправить оценки текущего контроля
(см. slemeshevsky.github.io)

7:46, Чт, 05.01.2017 Spinningcrane <notifications@github.com>:

**Comment by Spinningcrane** [comment]
Хорошо, спасибо, что продлили дедлайн. 
Я сделаю все возможное, чтобы увеличить объем сданных / переделанных лабораторных работ. Другие задания действительно сделать будет интереснее, чем переделывать старые.

**Comment by Spinningcrane** [comment]
Удалил все отбракованные лабораторные. Ниже напишу, что сделал и добавил, включая имена файлов, чтобы упростить поиск.

2.6: average_1_N
2.7: while_with_error
2.8: area_rectangle_vs_circle
2.9: cross_2_graphs
2.10: array_sorting
2.13: rand_frequency
2.14: game_21
#В заданиях .13 и .14 почему - то не захватывает верхнюю границу random.randint, поэтому пришлось делать с b+1, хотя во всех документациях указано, что меньше либо равно. Возможно дело в версиях питона.
